site_name:        MixedModels.jl
repo_url:         https://github.com/dmbates/MixedModels.jl
site_description: Fit and examine linear mixed-effects models
site_author:      Douglas M. Bates

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
